name: Java CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and run tests
        run: mvn clean verify

      - name: Generate JaCoCo report
        run: mvn jacoco:report

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/

      - name: Generate JaCoCo Badges
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          badges-directory: badges

      - name: Commit coverage badges
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update JaCoCo badges